//测试本地仓库中的插件
//buildscript {
//    repositories {
//        maven {
//            url uri('../PluginRepository')
//        }
//    }
//    dependencies {
//        classpath 'com.cdzyx.pushnotice:RootPush:1.0.0'
//    }
//}
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.cdzyx.rootpush"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        debug {
            storeFile file('tmsdriver.keystore')
            storePassword "tmsdriver2024"
            keyAlias "tmsdriver2024"
            keyPassword "tmsdriver2024"
        }
        release {
            storeFile file('tmsdriver.keystore')
            storePassword "tmsdriver2024"
            keyAlias "tmsdriver2024"
            keyPassword "tmsdriver2024"
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true//开启混淆
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            //可以不用限制 name != "debug"
            if (variant.buildType.name != "debug") {
                def time = new Date().format("yyyy-MM-dd-HH-mm", TimeZone.getTimeZone("GMT+08:00"))
                variant.packageApplication.outputDirectory = new File("${project.buildDir}/outputs/upload")
                outputFileName = "ZZ(Driver)-${variant.buildType.name}-v${variant.versionName}-${time}.apk"
            }
        }
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
//
//apply plugin: 'com.cdzyx.pushnotice'//使用自定义的插件
//
//uploadInfo {
//    needUpload = true
//    needAtPeopleMobiles = "张宇翔"
//    changeLog = "测试钉钉机器人(请勿下载)"
//    appTestVersionCodeText = "测试版本:test01"
//
//    //下面不用改
//    apiToken = "293457325da4b6363ecec48593d45fc4"
//    packageName = "com.tms.logistics"
//    robotToken = "82249f9cb272edcb47e8ac81a18a6e40db323175cfd24e61a7581c6e81bb8334"
//    appIconPath = project.projectDir.path + "/src/main/res/mipmap-xxhdpi/ic_launcher.png"
//    appName = "testpush"
//    firAppName = "RootPush"
//    platform = "dingding"
//    pgyApiKey="5019548c960ef9b00f6f9eb7b1062c89"
//}